version: '11'

services:
  postgresql-backend:
    image: 'bitnami/postgresql'
    ports:
      - "0.0.0.0:5435:5432"
    container_name: "postgresql_backend"
    volumes:
      - 'C:/Users/Dmitriy/.docker/postgresql:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=test