CREATE SEQUENCE topic_id_seq START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1;
ALTER TABLE topic ALTER COLUMN id SET DEFAULT nextval('topic_id_seq');
ALTER SEQUENCE topic_id_seq OWNED BY topic.id;